import assert from "node:assert/strict";
import { decideModelReadiness } from "../scripts/domain/model-readiness.mjs";
import { buildReadiness } from "../scripts/application/readiness-evidence.mjs";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
const root = fs.mkdtempSync(path.join(os.tmpdir(), "chapek-readiness-")); const models = path.join(root, "models"); const runtime = path.join(root, "runtime");
fs.mkdirSync(path.join(models, "worker"), { recursive: true }); fs.mkdirSync(path.join(runtime, "verification"), { recursive: true }); fs.mkdirSync(path.join(runtime, "capabilities"), { recursive: true });
const artifact = { repo: "org/model", quant: "Q4", modelId: "worker", files: [{ path: "model.gguf", size: 1, sha256: null }] };
fs.writeFileSync(path.join(models, "worker", "model.gguf"), "x"); fs.writeFileSync(path.join(models, "worker", "manifest.json"), JSON.stringify(artifact));
fs.writeFileSync(path.join(runtime, "verification", "worker.json"), JSON.stringify({ passed: true, artifact })); fs.writeFileSync(path.join(runtime, "capabilities", "worker.json"), JSON.stringify({ passed: true, artifact })); fs.writeFileSync(path.join(runtime, "calibration.json"), JSON.stringify({ profiles: { worker: { selected: {}, artifact } } }));
const [row] = buildReadiness({ profiles: { profiles: { worker: { repo: "org/model", quant: "Q4", supported: true } } }, modelsDir: models, runtimeDir: runtime }); assert.equal(row.eligible, true);
fs.writeFileSync(path.join(runtime, "verification", "worker.json"), JSON.stringify({ passed: true, artifact: { ...artifact, quant: "Q5" } }));
assert.equal(buildReadiness({ profiles: { profiles: { worker: { repo: "org/model", quant: "Q4", supported: true } } }, modelsDir: models, runtimeDir: runtime })[0].verification, false);
assert.ok(decideModelReadiness({ profile: { repo: "org/model", quant: "Q4", supported: false }, manifest: { repo: "org/model", quant: "Q4", files: [{ path: "model.gguf" }] }, verification: { passed: true }, calibration: { selected: {} }, capability: { passed: true } }).reasons.includes("capability-gated"));
fs.rmSync(root, { recursive: true, force: true }); console.log("readiness: ok");
